import { useState } from 'react';
import { Card } from '../components/ui/Card';
import { Badge } from '../components/ui/Badge';
import { CheckCircle2, AlertTriangle, AlertCircle, Bell, Search, Filter } from 'lucide-react';

const MOCK_ACTIVITIES = [
    { id: 1, type: 'success', title: 'Workflow "Lead Sync" Completed', message: 'Data sync to Salesforce finished successfully. 15 records updated.', time: '2 mins ago', date: 'Today' },
    { id: 2, type: 'warning', title: 'API Rate Limit', message: 'Approaching rate limit for GitHub API on "PR Notifier" workflow.', time: '15 mins ago', date: 'Today' },
    { id: 3, type: 'error', title: 'Connection Failed', message: 'Could not connect to PostgreSQL database in "Nightly Backup". Retrying in 5 mins.', time: '1 hour ago', date: 'Today' },
    { id: 4, type: 'info', title: 'Workspace Settings Updated', message: 'Jane Doe updated the workspace timezone to EST.', time: '3 hours ago', date: 'Today' },
    { id: 5, type: 'success', title: 'New Team Member', message: 'John Smith accepted the invitation and joined the workspace.', time: 'Yesterday', date: 'Yesterday' },
    { id: 6, type: 'info', title: 'API Key Generated', message: 'A new development API key was generated by Jane Doe.', time: 'Yesterday', date: 'Yesterday' },
    { id: 7, type: 'warning', title: 'Workflow "Customer Onboarding" Paused', message: 'Workflow paused due to 3 consecutive failures.', time: '2 days ago', date: 'Oct 12' },
];

export function Activities() {
    const [filter, setFilter] = useState('all');

    const filteredActivities = MOCK_ACTIVITIES.filter(activity => {
        if (filter === 'all') return true;
        return activity.type === filter;
    });

    const getIcon = (type: string) => {
        switch (type) {
            case 'success': return <CheckCircle2 className="w-5 h-5 text-status-success" />;
            case 'warning': return <AlertTriangle className="w-5 h-5 text-status-warning" />;
            case 'error': return <AlertCircle className="w-5 h-5 text-status-error" />;
            case 'info':
            default: return <Bell className="w-5 h-5 text-status-info" />;
        }
    };

    const getBadgeVariant = (type: string) => {
        switch (type) {
            case 'success': return 'success';
            case 'warning': return 'warning';
            case 'error': return 'error';
            case 'info':
            default: return 'info';
        }
    };

    return (
        <div className="p-8 max-w-5xl mx-auto h-[calc(100vh-64px)] flex flex-col">
            <div className="mb-6 flex items-center justify-between shrink-0">
                <div>
                    <h1 className="text-3xl font-bold text-text-primary">Activities</h1>
                    <p className="text-text-secondary mt-1">Review all workspace actions, workflow runs, and system notifications.</p>
                </div>

                <div className="flex items-center gap-3">
                    <div className="relative">
                        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-text-secondary" />
                        <input
                            type="text"
                            placeholder="Search activities..."
                            className="w-64 pl-9 pr-4 py-2 bg-white border border-border rounded-btn text-sm focus:outline-none focus:ring-2 focus:ring-primary/20"
                        />
                    </div>
                </div>
            </div>

            <div className="flex gap-6 flex-1 min-h-0">
                {/* Filters Sidebar */}
                <div className="w-56 shrink-0 space-y-6">
                    <Card className="p-4 bg-white/50 border-border/50">
                        <div className="flex items-center gap-2 mb-3 text-sm font-medium text-text-primary">
                            <Filter className="w-4 h-4" />
                            Filter by Type
                        </div>
                        <div className="space-y-1">
                            {[
                                { id: 'all', label: 'All Activities' },
                                { id: 'success', label: 'Success' },
                                { id: 'error', label: 'Errors' },
                                { id: 'warning', label: 'Warnings' },
                                { id: 'info', label: 'Info' },
                            ].map(item => (
                                <button
                                    key={item.id}
                                    onClick={() => setFilter(item.id)}
                                    className={`w-full text-left px-3 py-2 text-sm rounded-md transition-colors ${filter === item.id
                                            ? 'bg-primary text-white font-medium'
                                            : 'text-text-secondary hover:bg-background-canvas hover:text-text-primary'
                                        }`}
                                >
                                    {item.label}
                                </button>
                            ))}
                        </div>
                    </Card>
                </div>

                {/* Activity Feed */}
                <div className="flex-1 bg-white border border-border rounded-xl overflow-hidden flex flex-col">
                    <div className="overflow-y-auto p-4 space-y-4">
                        {filteredActivities.length > 0 ? (
                            filteredActivities.map((activity, index) => {
                                const showDateHeader = index === 0 || MOCK_ACTIVITIES[index - 1].date !== activity.date;

                                return (
                                    <div key={activity.id}>
                                        {showDateHeader && (
                                            <div className="sticky top-0 z-10 bg-white/95 backdrop-blur py-2 mb-3 border-b border-border text-xs font-semibold text-text-tertiary uppercase tracking-wider">
                                                {activity.date}
                                            </div>
                                        )}
                                        <div className="flex gap-4 p-4 rounded-lg bg-background-canvas/50 border border-border hover:bg-background-canvas transition-colors group">
                                            <div className="shrink-0 mt-1">
                                                {getIcon(activity.type)}
                                            </div>
                                            <div className="flex-1 min-w-0">
                                                <div className="flex justify-between items-start mb-1 gap-4">
                                                    <h3 className="text-sm font-semibold text-text-primary group-hover:text-primary transition-colors">
                                                        {activity.title}
                                                    </h3>
                                                    <span className="text-xs text-text-tertiary whitespace-nowrap shrink-0">
                                                        {activity.time}
                                                    </span>
                                                </div>
                                                <p className="text-sm text-text-secondary">
                                                    {activity.message}
                                                </p>
                                                <div className="mt-2 text-xs text-text-tertiary">
                                                    ID: ACT-{activity.id.toString().padStart(4, '0')}
                                                </div>
                                            </div>
                                            <div className="shrink-0 flex items-center">
                                                <Badge variant={getBadgeVariant(activity.type) as any} className="capitalize">{activity.type}</Badge>
                                            </div>
                                        </div>
                                    </div>
                                );
                            })
                        ) : (
                            <div className="flex flex-col items-center justify-center h-full text-text-secondary py-12">
                                <Filter className="w-12 h-12 text-text-tertiary mb-3 opacity-20" />
                                <p>No activities match your filters.</p>
                                <button
                                    onClick={() => setFilter('all')}
                                    className="mt-4 text-primary text-sm hover:underline font-medium"
                                >
                                    Clear all filters
                                </button>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
}
